name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13.0'  

      - name: Install Flutter SDK
        uses: subosito/flutter-action@v2

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build Flet App for Windows
        run: flet build windows

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: flet-app-windows
          path: dist/  

      - name: Create GitHub Release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref_name }}  
          release_name: "Release ${{ github.ref_name }}"  

      - name: Upload to Release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create-release.outputs.upload_url }}
          asset_path: dist/main.exe
          asset_name: main-${{ github.ref_name }}.exe  
          asset_content_type: application/octet-stream
